[package]
name = "gis-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-bytes = "0.1.0"
image = "0.24.7"
imageproc = "0.23.0"
regex = "1.10.2"
shapefile = "0.5.0"
